reliefweb_ai.settings:
  type: config_object
  label: 'ReliefWeb AI settings.'
  mapping:
    ocha_ai_chat:
      type: mapping
      label: 'Settings for the OCHA AI chat.'
      mapping:
        allow_for_anonymous:
          type: boolean
          label: 'Allow anonymous user to access the chat.'
        instructions_replace:
          type: boolean
          label: 'If TRUE, replace the chat instructions when the chat is disabled (error, anonymous access etc.), otherwise append the extra instructions.'
        login_instructions:
          type: text
          label: 'Login or register instructions for anonymous users.'
    language_detection:
      type: mapping
      label: 'Settings for the language detection.'
      mapping:
        tag:
          type: string
          label: 'XML tag in the LLM response from which to retrieve the text extracts.'
        use_title:
          type: boolean
          label: 'Whether to also use the title for the language detection.'
    text_extract_fix:
      type: mapping
      label: 'Settings for the text extraction fix.'
      mapping:
        tag:
          type: string
          label: 'XML tag in the LLM response from which to retrieve the extracted text.'
        line_matching:
          type: mapping
          label: 'Settings for the line matching between extracted text and original text.'
          mapping:
            endpoint:
              type: string
              label: 'OCHA AI helper to match lines.'
            threshold:
              type: integer
              label: 'Similary threshold.'
        inference:
          type: mapping
          label: 'Inference settings for the AI text fix.'
          mapping:
            plugin_id:
              type: string
              label: 'OCHA AI completion plugin ID.'
            temperature:
              type: float
              label: 'Temperature.'
            top_p:
              type: float
              label: 'Nucleus sampling (top_p).'
            max_tokens:
              type: integer
              label: 'Max tokens.'
            system_prompt:
              type: text
              label: 'System prompt.'
            prompt:
              type: text
              label: 'Prompt.'
