<?php

/**
 * @file
 * ReliefWeb revisions module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\reliefweb_revisions\Services\EntityHistory;

/**
 * Implements hook_theme().
 */
function reliefweb_revisions_theme() {
  $themes = [
    'reliefweb_revisions_history' => [
      'variables' => [
        // The headling level.
        'level' => 2,
        // Section attributes.
        'attributes' => NULL,
        // Section title.
        'title' => t('History'),
        // Entity whose history is displayed.
        'entity' => NULL,
        // history: list of revisions. Each revision has the following
        // properties:
        // - user: user who created the revision
        // - date: the revision timestamp
        // - status: associative array with the moderation status value and its
        //   label
        // - message: associative array with the revision log message and its
        //   type
        // - content: list of fields with their label and formatted differences.
        'history' => [],
      ],
    ],
  ];
  return $themes;
}

/**
 * Implements hook_form_HOOK_alter() for "node_form".
 */
function reliefweb_revisions_form_node_form_alter(array &$form, FormStateInterface $form_state) {
  EntityHistory::addHistoryToForm($form, $form_state);
}

/**
 * Implements hook_form_HOOK_alter() for "taxonomy_term_form".
 */
function reliefweb_revisions_form_taxonomy_term_form_alter(array &$form, FormStateInterface $form_state) {
  EntityHistory::addHistoryToForm($form, $form_state);
}
