<?php

/**
 * @file
 * Module file for the job importer.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\reliefweb_entities\Entity\Job;

/**
 * Implements hook_ENTITY_TYPE_presave() for node.
 */
function reliefweb_import_node_presave(EntityInterface $entity) {
  // @todo remove when removing `reliefweb_migrate`.
  if (!empty($entity->_is_migrating)) {
    return;
  }
  if ($entity instanceof Job && !empty($entity->_is_importing)) {
    $status = $entity->getModerationStatus();

    // Set the status to draft/on-hold if there were validation errors.
    if ($status !== 'refused' && !empty($entity->_import_errors)) {
      $status = \Drupal::state()->get('reliefweb_import_status_when_errors', 'draft');
      $entity->setModerationStatus($status);
    }

    // Set the revision user to the System user to differentiate modifications
    // made via the UI from automated ones. We need to do that here so that
    // the Job::preSave() uses the user associated with the import feed when
    // determining the status to use based on the user posting rights.
    $entity->setRevisionUserId(2);
  }
}
