<?php

/**
 * @file
 * Module file for the reliefweb_post_api module.
 */

declare(strict_types=1);

use Drupal\reliefweb_post_api\Entity\Provider;

/**
 * Implements hook_theme().
 */
function reliefweb_post_api_theme() {
  return [
    'reliefweb_api_user_dashboard' => [
      'variables' => [
        // Container attributes.
        'attributes' => NULL,
        // API key section with form to generate new key.
        'api_key' => NULL,
        // This is a list of API providers associated with the user.
        'providers' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_reliefweb_api_post_indexing().
 */
function reliefweb_post_api_reliefweb_api_post_indexing(string $entity_type_id, string $bundle, string|int|null $entity_id = NULL) {
  // We notify the Post API provider, if any, after the document is indexed in
  // the API otherwise the provider's webhook implementation will not be able to
  // to retrieve the data from the API to confirm the status.
  if (isset($entity_id)) {
    $entity = \Drupal::entityTypeManager()->getStorage($entity_type_id)->load($entity_id);
    if (!empty($entity)) {
      Provider::notifyProvider($entity);
    }
  }
}

/**
 * Implements hook_reliefweb_revisions_disallowed_fields_alter().
 */
function reliefweb_post_api_reliefweb_revisions_disallowed_fields_alter(array &$allowed, string $entity_type_id, string $bundle) {
  // Hide the post API fields.
  $allowed['field_post_api_provider'] = TRUE;
  $allowed['field_post_api_hash'] = TRUE;
}
