<?php

/**
 * @file
 * Module file for the ReliefWeb Fields module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\reliefweb_fields\Plugin\Field\FieldWidget\ReliefWebLinks;

/**
 * Implements hook_entity_type_build().
 */
function reliefweb_fields_entity_type_build(array &$entity_types) {
  $entity_types['taxonomy_term']->setFormClass('profile', 'Drupal\reliefweb_fields\Form\TaxonomyTermProfile');
}

/**
 * Implements hook_ENTITY_TYPE_update() for nodes.
 */
function reliefweb_fields_node_update(EntityInterface $entity) {
  ReliefWebLinks::updateFields('update', $entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete() for nodes.
 */
function reliefweb_fields_node_delete(EntityInterface $entity) {
  ReliefWebLinks::updateFields('delete', $entity);
}
