reliefweb_openai.settings:
  type: config_object
  label: 'Reliefweb OpenAI API settings'
  mapping:
    token:
      type: string
      label: 'OpenAI API key'
    api_org:
      type: string
      label: 'OpenAI organization ID'
