guidelines.guideline_type.*:
  type: config_entity
  label: 'Guideline type config'
  mapping:
    overwrite_description:
      type: boolean
      label: 'ID'
    use_json_loading:
      type: boolean
      label: 'ID'
