<?php

/**
 * @file
 * Reliefweb contact module.
 */

use Drupal\reliefweb_utility\Helpers\MailHelper;

/**
 * Implements hook_mail_alter().
 */
function reliefweb_contact_mail_alter(&$message) {
  if ($message['module'] !== 'contact' && $message['key'] !== 'user_mail') {
    return;
  }

  /** @var Drupal\contact\Entity\Message $contact_message */
  $contact_message = $message['params']['contact_message'];
  $sender = $contact_message->field_sender->value;

  // Set sender.
  /** @var \Drupal\Core\Field\FieldStorageDefinitionInterface $field_definition */
  $field_definition = $contact_message->field_sender->getFieldDefinition()->getFieldStorageDefinition();
  $field_allowed_options = options_allowed_values($field_definition, $contact_message);
  $sender_name = $field_allowed_options[$sender];

  // Clean subject.
  $config = \Drupal::config('system.site');
  $message['subject'] = t('[@site-name - @category] @subject', [
    '@site-name' => $config->get('name'),
    '@category' => $sender_name,
    '@subject' => $contact_message->subject->value,
  ]);

  // Replace the body from contact_mail() with the entered message content.
  $message['body'] = [check_markup($contact_message->message->value, 'plain_text')];

  // Plain text only.
  $message['params']['plaintext'] = MailHelper::getPlainText($message['body']);
  $message['params']['plain'] = TRUE;

  // Set sender headers.
  $message['from'] = $sender;
  $message['headers']['Bcc'] = $sender;
  $message['headers']['From'] = $sender_name . ' <' . $sender . '>';
  $message['headers']['Reply-to'] = $sender;
}
