<?php

/**
 * @file
 * Theme declaration etc. for the reliefweb_moderation module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Session\AccountInterface;
use Drupal\reliefweb_moderation\EntityModeratedInterface;
use Drupal\reliefweb_moderation\ModeratedNodeStorageSchema;
use Drupal\reliefweb_moderation\ModeratedTermStorageSchema;
use Drupal\reliefweb_moderation\ModerationServiceBase;

/**
 * Implements hook_theme().
 */
function reliefweb_moderation_theme() {
  $themes = [
    'reliefweb_moderation_page' => [
      'variables' => [
        // Entity list filters.
        'filters' => NULL,
        // Attributes for the filters.
        'filters_attributes' => NULL,
        // List of entities. @see reliefweb_moderation_table below.
        'list' => NULL,
        // Attributes for the list.
        'list_attributes' => NULL,
      ],
    ],
    'reliefweb_moderation_table' => [
      'variables' => [
        // Count of results per status. @see reliefweb_moderation_totals below.
        'totals' => NULL,
        // Headers for the table with the list of entities. In general it will
        // contain a header for the edit links, a header for the main entity
        // data and a header for the date, notably used for sorting.
        'headers' => [],
        // Table rows with entity information. It should contain cells as
        // describe above for the headers.
        'rows' => [],
        // Message for when there are no results.
        'empty' => '',
        // Pager.
        'pager' => NULL,
      ],
    ],
    'reliefweb_moderation_totals' => [
      'variables' => [
        // Associative array. Each item has the following keys:
        // - status: entity status
        // - label: entity status label
        // - total: number of entities with that status.
        'totals' => NULL,
      ],
    ],
    // Template for the moderation information (status, revision log message).
    'reliefweb_moderation_information' => [
      'variables' => [
        // Associative array with the moderation status value and its label.
        'status' => [],
        // Associative array with the type of message (feedback or
        // instruction), the message content and the message author.
        'message' => [],
      ],
    ],
    // Template to display a user posting right.
    'reliefweb_moderation_user_posting_right' => [
      'variables' => [
        // Wrapper attributes.
        'attributes' => NULL,
        // User posting right.
        'right' => '',
      ],
    ],
  ];
  return $themes;
}

/**
 * Implements hook_entity_base_field_info().
 */
function reliefweb_moderation_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  switch ($entity_type->id()) {
    case 'node':
      $fields['moderation_status'] = reliefweb_moderation_get_moderation_status_field_definition('draft');
      break;

    case 'taxonomy_term':
      $fields['moderation_status'] = reliefweb_moderation_get_moderation_status_field_definition('published');
      break;
  }

  return $fields;
}

/**
 * Implements hook_entity_type_alter().
 */
function reliefweb_moderation_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['node'])) {
    $entity_types['node']->setHandlerClass('storage_schema', ModeratedNodeStorageSchema::class);
  }
  if (isset($entity_types['taxonomy_term'])) {
    $entity_types['taxonomy_term']->setHandlerClass('storage_schema', ModeratedTermStorageSchema::class);
  }
}

/**
 * Get the moderation status field definition.
 *
 * @param string $default_status
 *   The default moderation status value.
 *
 * @return \Drupal\Core\Field\BaseFieldDefinition
 *   Field definition.
 */
function reliefweb_moderation_get_moderation_status_field_definition($default_status = 'draft') {
  return BaseFieldDefinition::create('string')
    ->setLabel(t('Moderation Status'))
    ->setSetting('max_length', 32)
    ->setRevisionable(TRUE)
    ->setTranslatable(TRUE)
    ->setDefaultValue($default_status)
    ->setDefaultValueCallback('reliefweb_moderation_moderation_status_value_callback');
}

/**
 * Moderation status default value callback.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity.
 * @param \Drupal\Core\Field\FieldDefinitionInterface $field_definition
 *   The moderation status field definition for the entity.
 *
 * @return string|null
 *   The moderation status if applicable for the
 */
function reliefweb_moderation_moderation_status_value_callback(EntityInterface $entity, FieldDefinitionInterface $field_definition) {
  if ($entity instanceof EntityModeratedInterface) {
    return $entity->getDefaultModerationStatus();
  }
  return $field_definition->getDefaultValueLiteral();
}

/**
 * Implements hook_entity_access().
 */
function reliefweb_moderation_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity instanceof EntityModeratedInterface) {
    $service = ModerationServiceBase::getModerationService($entity->bundle());
    if (!empty($service)) {
      return $service->entityAccess($entity, $operation, $account);
    }
  }
  // No opinion.
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_presave().
 */
function reliefweb_moderation_entity_presave(EntityInterface $entity) {
  if ($entity instanceof EntityModeratedInterface) {
    $service = ModerationServiceBase::getModerationService($entity->bundle());
    if (!empty($service)) {
      $service->entityPresave($entity);
    }
  }
}

/**
 * Implements hook_preprocess_page().
 *
 * Add the moderation information block to entity pages and forms.
 */
function reliefweb_moderation_preprocess_page(&$variables) {
  if (!\Drupal::currentUser()->hasPermission('access content moderation features')) {
    return;
  }

  $route_match = \Drupal::routeMatch();
  $entity = $route_match->getParameter('node') ?? $route_match->getParameter('taxonomy_term');

  // For existing revisionable and moderated entities, add the moderation
  // information at the top of the entity page/form.
  if (
      !empty($entity) &&
      $entity instanceof EntityModeratedInterface &&
      !$entity->isNew()
  ) {
    // Note: when comming back from the preview, the original revision log will
    // not be available...
    $message = $entity->getOriginalRevisionLogMessage();
    if (!empty($message)) {
      // Convert the message to markdown to generated links notably.
      // Wrap in a Markup so that the HTML is not escaped when rendered.
      $message = Markup::create(strip_tags(check_markup($message, 'markdown'), '<a><em><strong><br>'));
    }

    $element = [
      '#theme' => 'reliefweb_moderation_information',
      '#status' => [
        'value' => $entity->getModerationStatus(),
        'label' => $entity->getModerationStatusLabel(),
      ],
      '#message' => [
        'type' => $entity->getOriginalRevisionLogMessageType(),
        'content' => $message,
        'author' => $entity->getOriginalRevisionUser(),
      ],
      // Display the moderation information before the page title and local
      // tasks.
      '#weight' => -100,
      '#cache' => [
        '#tags' => [
          $entity->getEntityTypeId() . ':' . $entity->id(),
        ],
      ],
    ];

    $variables['page']['content']['moderation-information'] = $element;
  }
}
