<?php

/**
 * @file
 * Entity management for ReliefWeb.
 */

use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_entity_bundle_info_alter().
 *
 * Add bundle classes to nodes and terms to handle business logic.
 */
function reliefweb_entities_entity_bundle_info_alter(&$bundles) {
  $bundles['taxonomy_term']['country']['class'] = 'Drupal\reliefweb_entities\Entity\Country';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add suggestions for the view mode of the taxonomy terms.
 */
function reliefweb_entities_theme_suggestions_taxonomy_term_alter(array &$suggestions, array $variables) {
  /** @var \Drupal\taxonomy\TermInterface $term */
  $term = $variables['elements']['#taxonomy_term'];

  if (!empty($variables['elements']['#view_mode'])) {
    $view_mode = $variables['elements']['#view_mode'];
    $suggestions[] = 'taxonomy_term__' . $view_mode;
    $suggestions[] = 'taxonomy_term__' . $term->bundle() . '__' . $view_mode;
  }
}

/**
 * Implements hook_theme().
 */
function reliefweb_entities_theme() {
  return [
    'reliefweb_entities_table_of_contents' => [
      'variables' => [
        'level' => 2,
        'id' => 'table-of-contents',
        'title' => t('Table of Content'),
        'sections' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_token_info().
 *
 * Add content type token that returns "map" if the node is tagged with "Map".
 */
function reliefweb_entities_token_info() {
  $info = [];

  $info['tokens']['node']['reliefweb-content-type'] = [
    'name' => t('ReliefWeb - custom content type'),
    'description' => t('The unique machine-readable content type or map or infographic.'),
  ];

  return $info;
}

/**
 * Implements hook_tokens().
 *
 * @todo add token for the country shortname to use in report/job/training urls.
 */
function reliefweb_entities_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];

  if ($type == 'node' && !empty($data['node'])) {
    $node = $data['node'];

    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'reliefweb-content-type':
          // Use the bundle as content type.
          $replacements[$original] = $node->bundle();
          // Use "map" as content type for maps.
          if ($node->bundle() === 'report') {
            $content_format = $node->field_content_format->entity;
            if (!empty($content_format) && $content_format->label() === 'Map') {
              $replacements[$original] = 'map';
            }
          }
          break;
      }
    }
  }

  return $replacements;
}
