_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_denied: 0
  allowed_formats: 0
  amazon_ses: 0
  aws: 0
  block: 0
  book: 0
  breakpoint: 0
  ckeditor5: 0
  components: 0
  config: 0
  config_split: 0
  contact: 0
  content_entity_clone: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dynamic_page_cache: 0
  editor: 0
  environment_indicator: 0
  externalauth: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  geofield: 0
  gtm_barebones: 0
  guidelines: 0
  honeypot: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_binaries: 0
  imageapi_optimize_webp: 0
  imageapi_optimize_webp_responsive: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jsonlog: 0
  key: 0
  language: 0
  link: 0
  locale: 0
  mailsystem: 0
  maintenance200: 0
  media: 0
  media_library: 0
  memcache: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  mimemail: 0
  monitoring: 0
  mysql: 0
  node: 0
  ocha_ai: 0
  ocha_ai_chat: 0
  ocha_ai_tag: 0
  ocha_content_classification: 0
  ocha_monitoring: 0
  openid_connect: 0
  openid_connect_windows_aad: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  redirect: 0
  reliefweb_ai: 0
  reliefweb_analytics: 0
  reliefweb_api: 0
  reliefweb_bookmarks: 0
  reliefweb_contact: 0
  reliefweb_disaster_map: 0
  reliefweb_dsr: 0
  reliefweb_entities: 0
  reliefweb_entraid: 0
  reliefweb_fields: 0
  reliefweb_files: 0
  reliefweb_form: 0
  reliefweb_guidelines: 0
  reliefweb_homepage: 0
  reliefweb_import: 0
  reliefweb_job_tagger: 0
  reliefweb_meta: 0
  reliefweb_moderation: 0
  reliefweb_reporting: 0
  reliefweb_revisions: 0
  reliefweb_rivers: 0
  reliefweb_subscriptions: 0
  reliefweb_topics: 0
  reliefweb_user_history: 0
  reliefweb_user_posts: 0
  reliefweb_users: 0
  reliefweb_utility: 0
  reliefweb_xmlsitemap: 0
  responsive_image: 0
  seckit: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  sophron: 0
  svg_image: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_term_preview: 0
  text: 0
  theme_switcher: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  user_display_name: 0
  username_enumeration_prevention: 0
  workflows: 0
  pathauto: 1
  content_translation: 10
  views: 10
  minimal: 1000
theme:
  stable: 0
  classy: 0
  common_design: 0
  common_design_subtheme: 0
  claro: 0
profile: minimal
