module:
  admin_denied: 0
  allowed_formats: 0
  block: 0
  book: 0
  breakpoint: 0
  components: 0
  config: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  geofield: 0
  google_tag: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_binaries: 0
  inline_form_errors: 0
  language: 0
  link: 0
  locale: 0
  maintenance200: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  redirect: 0
  redis: 0
  reliefweb_migrate: 0
  responsive_image: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  pathauto: 1
  content_translation: 10
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  common_design: 0
  common_design_subtheme: 0
  seven: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
