_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  user__page:
    menu_name: account
    parent: ''
    weight: -10
    expanded: true
    enabled: true
  masquerade__unmasquerade:
    weight: -43
    parent: user.page
    menu_name: account
    enabled: true
    expanded: false
