format: html
name: ReliefWeb
mail: admin@reliefweb.int
linkonly: false
textonly: false
sitestyle: true
simple_address: false
preserve_class: false
advanced:
  incoming: false
  key: CFDxUu_9yazjn2xMq4S7MgFHeDGnZ6WahqWlpa5YQJI
_core:
  default_config_hash: rLKGzzC9TqjbEZiBoiyMpOSyZgldADa5SzvbA2gQDxE
