defaults:
  form:
    form_title: 'Ask ReliefWeb'
    popup_title: 'Ask about this document'
    instructions:
      value: "<p>Hi! I'm the ReliefWeb chat bot.</p><p>I can provide information about the document you're viewing.</p><p>Feel free to ask any questions!</p>"
      format: markdown_editor
    feedback: both
    formatting: basic
    answers:
      no_document: 'Sorry, no source documents were found.'
      no_passage: 'Sorry, I could not find information to answer the question.'
      no_answer: 'Sorry, I was unable to answer your question. Please try again in a short moment.'
      invalid_answer: "Sorry, I'm unable to answer your question. Please clarify."
      document_embedding_error: 'Sorry, there was an error trying to retrieve the documents to answer your question.'
      question_embedding_error: 'Sorry, there was an error trying to process the question.'
  plugins:
    answer_validator:
      plugin_id: similarity_embedding
    completion:
      plugin_id: aws_bedrock_titan_text_premier_v1
    embedding:
      plugin_id: aws_bedrock_titan_embed_text_v2
    ranker:
      plugin_id: NULL
      limit: 5
    source:
      plugin_id: reliefweb
      reliefweb:
        url: ''
        limit: 1
        editable: 0
        open: 0
        display: 0
    text_extractor:
      application/pdf:
        plugin_id: mupdf
    text_splitter:
      plugin_id: token
      length: 180
      overlap: 0
    vector_store:
      plugin_id: elasticsearch_flattened
