_core:
  default_config_hash: r1hk7e31MjYWgy4AuBRXxwuhornPFBp0LDrncwSG38Q
defaults:
  form:
    instructions:
      value: 'The process of posting jobs via ReliefWeb is now even smoother. The form now includes an automated function for the "career" and "themes" categories; fewer fields for users to fill and higher efficiency overall.'
      format: markdown_editor
  plugins:
    completion:
      plugin_id: aws_bedrock
    embedding:
      plugin_id: aws_bedrock
    source:
      plugin_id: reliefweb
    text_extractor:
      application/pdf:
        plugin_id: mupdf
    text_splitter:
      plugin_id: token
    vector_store:
      plugin_id: elasticsearch
