always_save_userinfo: true
connect_existing_users: true
override_registration_settings: false
end_session_enabled: true
user_login_display: below
redirect_login: ''
redirect_logout: /
userinfo_mappings:
  timezone: zoneinfo
  user_picture: picture
role_mappings: {  }
