enabled: 1
max_import_attempts: 3
api_url: 'https://data.unhcr.org'
api_key: REPLACE_WITH_API_KEY
list_endpoint: /api-content/documents.json
document_endpoint: '/api-content/documents/{{id}}.json'
timeout: 30
