enabled: true
max_import_attempts: 3
classification:
  enabled: true
  check_user_permissions: false
  prevent_publication: false
  force_field_update: '*:no'
  classified_fields: '*:yes'
  specifield_field_check: '*:no'
email: info@example.com
password: xyzzy
app_id: '123'
app_key: abc
api_url: 'https://www.inoreader.com/reader/api/0/stream/contents/user%2F-%2Flabel%2Fautomation_good?n=100&r=o'
timeout: '10'
