enabled: true
max_import_attempts: 3
classification:
  enabled: true
  check_user_permissions: false
  prevent_publication: true
  specifield_field_check: '*:no'
  force_field_update: "*:yes\r\ntitle__value:no\r\nfield_source:no"
  classified_fields: '*:yes'
api_url: 'https://data.unhcr.org'
api_key: REPLACE_WITH_API_KEY
list_endpoint: /api-content/documents.json
document_endpoint: '/api-content/documents/{{id}}.json'
timeout: 30
