enabled: true
max_import_attempts: 3
classification:
  enabled: false
  check_user_permissions: false
  prevent_publication: false
  specifield_field_check: ''
  force_field_update: ''
  classified_fields: ''
api_url: 'https://erccportal.jrc.ec.europa.eu/API/ERCC/EchoFlash/GetPagedItems?ItemsCurrentPageIndex=1&ItemsPageSize=50&Filter%5BStatus%5D%5B%5D=Published'
timeout: 60
