allowed_social_media_links:
  facebook: Facebook
  instagram: Instagram
  medium: Medium
  linkedin: LinkedIn
  twitter: Twitter
  youtube: YouTube
cron:
  embargoed_reports_limit: 20
  expired_jobs_limit: 20
  expired_training_limit: 20
