base_url: 'https://auth.humanitarian.id'
auto_redirect: true
disable_default: true
disable_password_fields: true
disable_email_field: true
disable_user_field: true
_core:
  default_config_hash: B3_vC6x6B42V4R6M9ydwieDSue2W-7J4HLg2z9avqh8
client_id: CLIENT_ID
client_secret: SECRET
maintenance_access: false
