client_id: REPLACE
client_secret: REPLACE
scopes: ''
endpoints: ''
tenant_id: ''
account_type: common
allowed_domains: ''
use_legacy_urls: true
login_behavior: register_and_login
block_user_1: true
block_admin_role: true
