_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: a475b4b3-5bfb-45b7-887d-f6b8eb50a6fd
name: ReliefWeb
mail: donotreply@reliefweb.int
slogan: 'The leading humanitarian information source on global crises and disasters. Reliable and timely information from trusted sources.'
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: donotreply@reliefweb.int
