#!/bin/sh

# Lint php and css code.

# We only lint files from custom modules.
# We ignore generated css files (styles*.css), sass and javascript files which
# are linted separately, images and XSL files.
include='^html/(modules|themes)/custom'
exclude='(\.(js|ico|png|jpg|gif|svg|scss|xsl)$)'

# Assume that the php command is global.
linter="php"
options='-l'
message='Linting staged PHP files...'

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
