#!/bin/sh

# Lint sass files.

# We only lint files from custom themes.
include='^html/themes/custom/common_design_subtheme/.*\.scss$'
exclude=' '

# The linter path is relative to the root of the repository.
relative=1
linter="html/themes/custom/common_design_subtheme/node_modules/.bin/sass-lint"
options='-v -q --max-warnings 0 -c html/themes/custom/common_design_subtheme/.sass-lint.yml'
message='Linting staged SASS files...'

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
