#!/bin/sh

# Lint CSS and SASS files.

# We only lint files from the custom themes and modules.
include='^(html/themes/custom/[^/]+/(sass|components)|html/modules/custom)/.*\.s?css$'
exclude='(node_modules|vendor)'

# The linter path is relative to the root of the repository.
relative=1
linter="html/themes/custom/common_design_subtheme/node_modules/.bin/stylelint"
options=""
message='Linting subtheme CSS/SCSS files...'
# We need to change to the linter's directory to load its dependencies.
changedir=1

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
