#!/bin/sh

# Lint sass files.

# We only lint files from custom themes.
include='^html/themes/custom/common_design_subtheme/.*\.scss$'
exclude=' '

# The linter path is relative to the root of the repository.
relative=1
linter="html/themes/custom/common_design_subtheme/node_modules/.bin/stylelint"
options="'{sass,components}/**/*.{css,scss}'"
message='Linting subtheme CSS/SCSS files...'

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
