<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function reliefweb_bookmarks_help($route_name) {
  switch ($route_name) {
    case 'help.page.reliefweb_bookmarks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Reliefweb bookmarks module is very useful for the site with large content. This module allow site visitors to add any node into there bookmarks and then they can read later.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_preprocess_node().
 */
function reliefweb_bookmarks_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];
  $config = \Drupal::config('reliefweb_bookmarks.settings');
  if (!isset($config->get('content_types')[$node->getType()]) || !$config->get('content_types')[$node->getType()]) {
    return;
  }

  if (!\Drupal::currentUser()->id()) {
    return;
  }

  $links[] = reliefweb_bookmarks_build_link('node', $node->id(), \Drupal::currentUser()->id());

  $variables['content']['reliefweb_bookmarks_link'] = [
    '#theme' => 'links',
    '#title' => t('Bookmark'),
    '#links' => $links,
    '#attached' => [
      'library' => [
        'core/drupal.ajax',
      ],
    ],
    '#cache' => [
      'contexts' => [
        'user',
      ],
      'tags' => [
        'user:' . \Drupal::currentUser()->id(),
        'reliefweb_bookmarks:user:' . \Drupal::currentUser()->id(),
        'reliefweb_bookmarks:entity_id:' . $node->id(),
      ],
    ],
  ];
}

/**
 * Build bookmark link.
 */
function reliefweb_bookmarks_build_link($entity_type, $entity_id, $uid) {
  // Only nodes for now.
  if ($entity_type !== 'node') {
    return;
  }

  $request = \Drupal::destination();
  $path = '/node/' . $entity_id . '/add-to-bookmarks';
  $url = Url::fromUri('internal:' . $path, [
    'query' => ['destination' => $request->get()],
    'absolute' => TRUE,
  ]);

  $db = \Drupal::database();
  $query = $db->select('reliefweb_bookmarks', 'ew');
  $query->fields('ew');
  $query->condition('entity_type', $entity_type);
  $query->condition('entity_id', $entity_id);
  $query->condition('uid', $uid);
  $check_entry = $query->execute()->FetchField();

  if ($check_entry) {
    $label = t('Remove from bookmarks');
  }
  else {
    $label = t('Add to bookmarks');
  }

  return [
    'title' => $label,
    'url' => $url,
    'attributes' => [
      'class' => [
        'use-ajax',
        'bookmark--link',
        $check_entry ? 'bookmark--link--remove' : 'bookmark--link--add',
      ],
    ],
  ];
}

/**
 * Toggle bookmark.
 */
function reliefweb_bookmarks_toggle_bookmark($entity_type, $entity_id, $uid) {
  $query = \Drupal::database()->select('reliefweb_bookmarks', 'ew');
  $query->fields('ew');
  $query->condition('entity_type', $entity_type);
  $query->condition('entity_id', $entity_id);
  $query->condition('uid', $uid);
  $check_entry = $query->execute()->FetchField();

  if ($check_entry) {
    $query = \Drupal::database()->delete('reliefweb_bookmarks');
    $query->condition('entity_type', $entity_type);
    $query->condition('entity_id', $entity_id);
    $query->condition('uid', $uid);
    $query->execute();
  }
  else {
    \Drupal::database()->insert('reliefweb_bookmarks')
      ->fields(
        [
          'entity_type' => $entity_type,
          'entity_id' => $entity_id,
          'uid' => $uid,
        ]
    )->execute();
  }

  return $check_entry;
}
