reliefweb_dsr.settings:
  type: config_object
  label: 'ReliefWeb DSR settings'
  mapping:
    ctf_cda_access_token:
      type: string
      label: 'ContentFul API access token.'
    ctf_dsr_url:
      type: string
      label: 'ContentFul DSR UR.L'
    ocha_dsr_url:
      type: string
      label: 'OCHA DSR site URL.'
    cache_lifetime:
      type: integer
      label: 'Number of seconds to cache the data for.'
    last_update_skip:
      type: integer
      label: 'Skip of the situation report has n0t been updated for X days.'
    show_illustration:
      type: boolean
      label: 'Whether to show the DSR illustration or not.'
