field.field_settings.reliefweb_links:
  type: mapping
  label: 'Reliefweb links settings'
  mapping:
    internal:
      type: boolean
      label: 'Internal links'
    use_cover:
      type: boolean
      label: 'Use cover'
    keep_archives:
      type: boolean
      label: 'Keep archives'

field.field_settings.reliefweb_section_links:
  type: mapping
  label: 'Reliefweb section links settings'
  mapping:
    use_override:
      type: boolean
      label: 'Use override'
    use_title:
      type: boolean
      label: 'Use title'
    rivers:
      type: sequence
      sequence:
        -  type: string
           label: 'River name'
