field.widget.settings.reliefweb_entity_reference_select:
  type: mapping
  label: 'ReliefWeb Entity Reference Select widget settings'
  mapping:
    sort:
      type: string
      label: 'Sort'
    extra_data:
      type: sequence
      label: 'Extra data'
      sequence:
        - type: string
          label: 'Extra data'

field.widget.settings.reliefweb_formatted_text:
  type: mapping
  label: 'ReliefWeb Formatted Text widget settings'
  mapping:
    max_heading_level:
      type: integer
      label: 'Maximum heading level'
    strip_embedded_content:
      type: boolean
      label: 'Strip embedded content'
