field.field_settings.reliefweb_links:
  type: mapping
  label: 'Reliefweb links settings'
  mapping:
    internal:
      type: boolean
      label: 'Internal links'
    use_cover:
      type: boolean
      label: 'Use cover'
    keep_archives:
      type: boolean
      label: 'Keep archives'
