reliefweb_files.settings:
  type: config_object
  label: 'ReliefWeb Docstore settings'
  mapping:
    docstore_url:
      type: string
      label: 'The URL of the OCHA docstore.'
    docstore_provider_uuid:
      type: string
      label: 'The UUID of the provider in the OCHA docstore.'
    docstore_api_key:
      type: string
      label: 'The API key for the OCHA docstore provider.'
    docstore_prefix:
      type: string
      label: 'The prefix used when creating new content (ex: reliefweb_reports).'
    local:
      type: boolean
      label: 'Flag to store the files locally instead of remotely'
    file_directory:
      type: string
      label: 'Name of the directory for the local file attachments.'
    preview_directory:
      type: string
      label: 'Name of the directory for the local file previews.'

field.field_settings.reliefweb_file:
  type: mapping
  mapping:
    file_extensions:
      type: string
      label: 'Allowed file extensions'
    max_filesize:
      type: string
      label: 'Maximum upload size'
    preview_max_filesize:
      type: string
      label: 'Preview maximum upload size'
    preview_min_dimensions:
      type: string
      label: 'Preview minimum dimensions in the form WIDTHxHEIGHT'

field.widget.settings.reliefweb_file:
  type: mapping
  label: 'ReliefWeb File widget settings'
  mapping:
    extensions:
      type: string
      label: 'Allowed file extensions.'
    max_file_size:
      type: integer
      label: 'Allowed max file size.'
    duplicate_max_documents:
      type: integer
      label: 'Maximum number of similar documents to return.'
    duplicate_minimum_should_match:
      type: string
      label: 'Minimum similarity threshold for duplicate detection.'
    duplicate_warning_message:
      type: string
      label: 'Warning message to display when duplicates are found.'

field.widget.settings.reliefweb_file_simplified:
  type: field.widget.settings.reliefweb_file
  label: 'ReliefWeb File Simplified widget settings'
