reliefweb_import.settings:
  type: config_object
  label: 'ReliefWeb import settings'
  mapping:
    extract_url:
      type: string
      label: 'The URL of the extract service.'

reliefweb_import.workday.*:
  type: config_object
  label: 'ReliefWeb WorkDay job import settings'
  mapping:
    name:
      type: string
      label: 'The WorkDay tenant name.'
    enabled:
      type: boolean
      label: 'Whether the WorkDay job import is enabled or not.'
    base_url:
      type: string
      label: 'The URL of the WorkDay API.'
    tenant:
      type: string
      label: 'The WorkDay tenant.'
    client_id:
      type: string
      label: 'The WorkDay API client ID.'
    client_secret:
      type: string
      label: 'The WorkDay API client secret.'
    refresh_token:
      type: string
      label: 'The WorkDay API refresh token.'
    timeout:
      type: integer
      label: 'The HTTP request timeout in seconds.'
    source_id:
      type: integer
      label: 'The source ID to assign to imported jobs.'
    uid:
      type: integer
      label: 'The user ID to assign as owner of imported jobs.'

# Importer plugin base settings.
reliefweb_import.plugin.importer:
  type: mapping
  label: 'ReliefWeb importer plugin base settings.'
  mapping:
    enabled:
      type: boolean
      label: 'Whether the plugin is enabled or not.'
    provider_uuid:
      type: string
      label: 'UUID of the Post API provider used associated with this importer plugin.'
    max_import_attempts:
      type: integer
      label: 'Maximum number of import attempts for an item before considering the import as failure.'
    classification:
      type: mapping
      label: 'Automated classification settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable classification.'
        check_user_permissions:
          type: boolean
          label: 'Check the user permissions to use the classification.'
        prevent_publication:
          type: boolean
          label: 'Prevent entity publication while being classified'
        specified_field_check:
          type: string
          label: 'Control which fields should be checked for emptiness before classification.'
        force_field_update:
          type: string
          label: 'Control which fields should be updated even if already filled.'
        classified_fields:
          type: string
          label: 'Control which fields should be updated with classifier results.'
    reimport:
      type: mapping
      label: 'Reimport settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable reimport.'
        type:
          type: string
          label: 'Type of reimport based on entity moderation status.'
        fields:
          type: string
          label: 'Control which fields should be updated when reimporting.'
        statuses:
          type: string
          label: 'Moderation status mapping.'

# UNHCR Data importer plugin settings.
reliefweb_import.plugin.importer.unhcr_data:
  type: reliefweb_import.plugin.importer
  label: 'UNHCR Data importer plugin base settings.'
  mapping:
    api_url:
      type: string
      label: 'API URL.'
    api_key:
      type: string
      label: 'API key.'
    list_endpoint:
      type: string
      label: 'Endpoint path to get a list of documents.'
    document_endpoint:
      type: string
      label: 'Endpoint path to get a document.'
    timeout:
      type: integer
      label: 'Connection and request timeout.'

# ECHO Flash Update importer plugin settings.
reliefweb_import.plugin.importer.echo_flash_update:
  type: reliefweb_import.plugin.importer
  label: 'ECHO Flash Update importer plugin base settings.'
  mapping:
    api_url:
      type: string
      label: 'API URL.'
    timeout:
      type: integer
      label: 'Connection and request timeout.'

# ECHO Map importer plugin settings.
reliefweb_import.plugin.importer.echo_map:
  type: reliefweb_import.plugin.importer
  label: 'ECHO Map importer plugin base settings.'
  mapping:
    api_url:
      type: string
      label: 'API URL.'
    file_url_pattern:
      type: string
      label: 'File download URL pattern with a `@id` placeholder that is replaced by the document ID.'
    timeout:
      type: integer
      label: 'Connection and request timeout.'

# Inoreader importer plugin settings.
reliefweb_import.plugin.importer.inoreader:
  type: reliefweb_import.plugin.importer
  label: 'Inoreader importer plugin settings.'
  mapping:
    email:
      type: string
      label: 'Email.'
    password:
      type: string
      label: 'Password.'
    app_id:
      type: string
      label: 'App Id.'
    app_key:
      type: string
      label: 'App key.'
    api_url:
      type: string
      label: 'API URL.'
    timeout:
      type: integer
      label: 'Connection and request timeout.'
    fetch_timeout:
      type: integer
      label: 'Connection and request timeout to grab external pages.'
    local_file_load:
      type: boolean
      label: 'Load json from local file.'
    local_file_save:
      type: boolean
      label: 'Dump json to local file.'
    local_file_path:
      type: string
      label: 'Local file path.'

# WFP Logcluster importer plugin settings.
reliefweb_import.plugin.importer.wfp_logcluster:
  type: reliefweb_import.plugin.importer
  label: 'WFP Logcluster importer plugin settings.'
  mapping:
    api_url:
      type: string
      label: 'API URL.'
    api_key:
      type: string
      label: 'API Key.'
    max_age:
      type: integer
      label: 'Max age in days.'
    skip_document_types:
      type: string
      label: List of Logistic Cluster document types to skip.'
    timeout:
      type: integer
      label: 'Connection and request timeout.'

# Worldbank importer plugin settings.
reliefweb_import.plugin.importer.worldbank:
  type: reliefweb_import.plugin.importer
  label: 'Worldbank importer plugin base settings.'
  mapping:
    api_url:
      type: string
      label: 'API URL.'
    max_age:
      type: integer
      label: 'Max age in days.'
    themes_to_import:
      type: string
      label: List of Worldbank themes to import.'
    document_types_to_import:
      type: string
      label: List of Worldbank document types to import.'
    timeout:
      type: integer
      label: 'Connection and request timeout.'

# UNEP importer plugin settings.
reliefweb_import.plugin.importer.unep:
  type: reliefweb_import.plugin.importer
  label: 'UNEP importer plugin base settings.'
  mapping:
    api_url:
      type: string
      label: 'API URL.'
    api_key:
      type: string
      label: 'API Key.'
    max_age:
      type: integer
      label: 'Max age in days.'
    document_types:
      type: string
      label: List of document types to import.'
    timeout:
      type: integer
      label: 'Connection and request timeout.'
