name: Run Composer Update

on:
  schedule:
    - cron: '20 21 * * 3'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Update The Thing
      id: update-action
      uses: UN-OCHA/actions/composer-update@main
      with:
        aws_role: ${{ vars.AWS_ROLE }}
        aws_region: ${{ vars.AWS_REGION }}
        aws_account: ${{ vars.AWS_ACCOUNT }}
        github_access_token: ${{ secrets.PAT }}
        patch_branch: ${{ github.head_ref || github.ref_name }}
        patch_maintainers: ${{ vars.DRUPAL_MAINTAINERS }}
        patch_packages: "drupal/* unocha/* drush/* google/* league/* weitzman/drupal-test-traits"
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack_channel_name: ${{ vars.SLACK_CHANNEL }}
        source_directory: html/modules/custom,html/themes/custom
        output_format: "table"
        composer_scripts: "true"
